##################################################################################
#
# Laravel API Response Builder Travis CI config file
#
# @package   MarcinOrlowski\ResponseBuilder
#
# @author    Marcin Orlowski <mail (#) marcinorlowski (.) com>
# @copyright 2016-2019 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/laravel-api-response-builder
#
##################################################################################

language: php

# Enforcing Ubuntu Trusty to keep PHP 5.5 support
# https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
dist: trusty

php:
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION="6.0"
  - LARAVEL_VERSION="6.2"
  - LARAVEL_VERSION="6.3"

#matrix:
#  exclude:
#    - php: 7.1
#      env: LARAVEL_VERSION="6.0"

cache:
  directories:
    - ${HOME}/.composer/cache/files

before_script:
  - cp -f "travis/composer-${LARAVEL_VERSION}.json" composer.json
  - FLAGS="--prefer-dist"
  - composer install "${FLAGS}"
  # We need to tweak signature of setUp() and tearDown() methods and strip ": void" otherwise PHP will
  # fail complaining. This affects Laravel 5.8+ and 6.x (up to 6.3 for now) as they pull recent Orchestra
  # that features method signature changes.
  - sed -i 's/): void/)/' vendor/orchestra/testbench-core/src/TestCase.php
  - sed -i 's/): void/)/' vendor/phpunit/phpunit/src/Framework/TestCase.php

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover /tmp/coverage.xml

after_success:
  # If coverage file is generated then upload it to Codacy (requires CODACY_PROJECT_TOKEN= env var set).
  - if [[ -f /tmp/coverage.xml ]]; then vendor/bin/codacycoverage clover /tmp/coverage.xml ; fi
  # Scrunitizer-CI
  - if [[ -f /tmp/coverage.xml ]]; then wget --output-document=/tmp/ocular.phar https://scrutinizer-ci.com/ocular.phar && php /tmp/ocular.phar code-coverage:upload --format=php-clover /tmp/coverage.xml ; fi
