##################################################################################
#
# Laravel API Response Builder Travis CI config file
#
# @package   MarcinOrlowski\ResponseBuilder
#
# @author    Marcin Orlowski <mail (#) marcinOrlowski (.) com>
# @copyright 2016-2020 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/laravel-api-response-builder
#
##################################################################################

language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - LARAVEL_VERSION="6.0"
  - LARAVEL_VERSION="6.2"
  - LARAVEL_VERSION="6.3"
  - LARAVEL_VERSION="6.4"
  - LARAVEL_VERSION="6.5"
  - LARAVEL_VERSION="6.6"
  - LARAVEL_VERSION="6.7"
  - LARAVEL_VERSION="6.8"
  - LARAVEL_VERSION="7.0"
  - LARAVEL_VERSION="8.0"

matrix:
  exclude:
    - php: 7.2
      env: LARAVEL_VERSION="8.0"

cache:
  directories:
    - ${HOME}/.composer/cache/files

before_script:
  - cp -f "travis/composer-laravel-${LARAVEL_VERSION}.json" composer.json
  - composer install --prefer-dist
  # Need to tweak signature of setUp() and tearDown() methods and strip the ": void" from it, otherwise tests
  # run will fail due to signature mismatch. This affects Laravel 5.8+ and 6.x as they pull recent Orchestra
  # version that features methods' signature change.
  - "sed -i 's/): void/)/' vendor/orchestra/testbench-core/src/TestCase.php"
  - "sed -i 's/): void/)/' vendor/phpunit/phpunit/src/Framework/TestCase.php"

script:
  - vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover /tmp/clover.xml

after_success:
  # If coverage file is generated then upload it to Codacy (requires CODACY_PROJECT_TOKEN= env var set).
  - bash <(wget -q -O - https://coverage.codacy.com/get.sh) report -l PHP -r /tmp/clover.xml
  # Scrutinizer-CI
  - wget --output-document=/tmp/ocular.phar https://scrutinizer-ci.com/ocular.phar && php /tmp/ocular.phar code-coverage:upload --format=php-clover /tmp/clover.xml
