##################################################################################
#
# Laravel API Response Builder
#
# @package   MarcinOrlowski\ResponseBuilder
#
# @author    Marcin Orlowski <mail (#) marcinorlowski (.) com>
# @copyright 2016-2017 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/laravel-api-response-builder
#
##################################################################################

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - LARAVEL_VERSION="5.1"
  - LARAVEL_VERSION="5.2"
  - LARAVEL_VERSION="5.3"
  - LARAVEL_VERSION="5.4"

matrix:
  exclude:
    - php: 5.5
      env: LARAVEL_VERSION="5.3"
    - php: 5.5
      env: LARAVEL_VERSION="5.4"

cache:
  directories:
    - ${HOME}/.composer/cache/files

before_script:
#   Disable coverage (hhvm does not feature xdebug)
  - if [ $TRAVIS_PHP_VERSION != hhvm ] ; then phpenv config-rm xdebug.ini ; fi
  - cp -f "travis/composer-${LARAVEL_VERSION}.json" composer.json
  - FLAGS="--prefer-dist"
  - composer install ${FLAGS}

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover /tmp/coverage.xml

after_success:
#   IF coverage file is generated then upload it to Codacy
  - if [ -f /tmp/coverage.xml ] ; then vendor/bin/codacycoverage clover /tmp/coverage.xml ; fi
